"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Button, Layout, Menu, theme } from "antd";
import { MenuFoldOutlined, MenuUnfoldOutlined } from "@ant-design/icons";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const { Header, Sider, Content } = Layout;

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [collapsed, setCollapsed] = useState(true);
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();

  const authRouter = ["/", "/forgot-password"];

  return (
    <html lang="en">
      {authRouter.includes(window?.location?.pathname) ? (
        <body>{children}</body>
      ) : (
        <body>
          <Layout className="mg-das-wrapper">
            <Sider
              trigger={null}
              collapsible
              collapsed={collapsed}
              className="side-bar"
            >
              <div>
                <img src="/assets/tiger-icon.png" />
              </div>
              <div className="side-icon-styles">
                <img src="/assets/menu.svg" />
              </div>
              <div className="side-icon-styles">
                <img src="/assets/target.svg" />
              </div>
              <div>
                <img src="/assets/Deals.svg" />
              </div>
              <div className="side-icon-styles p-15">
                <img src="/assets/profile.svg" />
              </div>
              <div className="side-icon-styles">
                <img src="/assets/Group.svg" />
              </div>
            </Sider>
            <Layout>
              <Header style={{ padding: 0, background: colorBgContainer }}>
                <span className="platform-name">Tiger Sports</span>
              </Header>

              <Content
                style={{
                  margin: "24px 16px",
                  padding: 24,
                  minHeight: 280,
                }}
              >
                {children}
              </Content>
            </Layout>
          </Layout>
        </body>
      )}
    </html>
  );
}
